name: ml_preprocessing
description: Implementaion of popular algorithms of data preprocessing for machine learning
version: 3.4.0+1
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_preprocessing

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  ml_linalg: ^10.0.3
  ml_dataframe:
    git:
      url: https://github.com/gyrdym/ml_dataframe.git
  csv: ^4.0.0
  tuple: ^1.0.2
  xrange: ^0.0.4
  quiver: ^2.0.2

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
