name: ml_preprocessing
description: Implementaion of popular algorithms of data preprocessing for machine learning
version: 2.0.0
author: Ilia Gyrdymov <ilgyrd@gmail.com>
homepage: https://github.com/gyrdym/ml_preprocessing

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  csv: ^4.0.0
  ml_linalg: ^6.1.1
  tuple: ^1.0.2

dev_dependencies:
  benchmark_harness: ">=1.0.0 <2.0.0"
  test: ^1.2.0
  mockito: ^3.0.0
  build_runner: ^1.1.2
  build_test: ^0.10.2
