name: ml_preprocessing
description: Popular data preprocessing algorithms for machine learning
version: 7.0.2
publish_to: none
homepage: https://github.com/gyrdym/ml_preprocessing

environment:
  sdk: ^3.1.3

dependencies:
  ml_dataframe:
    git:
      url: https://github.com/ArunBabu98/ml_dataframe
      ref: xena
  ml_linalg:
    git:
      url: https://github.com/ArunBabu98/ml_linalg
      ref: xena
  quiver: ^3.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  mockito: ^5.0.2
  pedantic: ^1.11.0
  test: ^1.16.8
